In [1]:
import numpy as np

1) Buat tensor 

2) Perkalian matrix

In [11]:
A = np.array([[23,50,19], 
              [7,12,109], 
              [57,67,98]])
B = np.array([[17],
              [22],
              [19]])


In [12]:
# A x B 
print(A@B)

[[1852]
 [2454]
 [4305]]


3) Find transpose, determinent, inverse of matrix A 

In [13]:
# transpose matrix A 
print(A)
print('transponse:\n', A.T)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
transponse:
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [14]:
# hitung determinant 
print(np.linalg.det(A))

131344.0000000002


In [16]:
# inverse matrix A 
print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
